# Generated by Django 4.2.7 on 2024-08-23 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_available', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_available',
            name='quantity_available',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
