# Generated by Django 4.2.7 on 2024-08-23 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_available', '0002_product_available_quantity_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_available',
            name='measure',
            field=models.CharField(choices=[('kgs', 'kgs'), ('units', 'units'), ('litres', 'litres')], default=0, max_length=100),
            preserve_default=False,
        ),
    ]
