# Generated by Django 4.2.7 on 2024-08-24 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_available', '0003_product_available_measure'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_available',
            name='measure',
        ),
    ]
