# Generated by Django 4.2.7 on 2024-08-23 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_order',
            name='measure',
            field=models.CharField(blank=True, choices=[('kgs', 'kgs'), ('units', 'units'), ('litres', 'litres')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='product_order',
            name='quantity_required',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
