# Generated by Django 4.2.7 on 2024-08-24 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_order', '0002_product_order_measure_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_order',
            name='measure',
        ),
    ]
