# Generated by Django 4.2.7 on 2024-08-23 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_product_measure_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_id',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shop',
            name='shop_id',
            field=models.CharField(default=1213123, max_length=100),
            preserve_default=False,
        ),
    ]
