# Generated by Django 4.2.7 on 2024-08-24 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_product_product_id_shop_shop_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='measure',
            field=models.CharField(choices=[('kgs', 'kgs'), ('units', 'units'), ('litres', 'litres')], default=0, max_length=100),
            preserve_default=False,
        ),
    ]
